from __future__ import annotations

from datetime import datetime, timedelta

from sqlalchemy import select
from sqlalchemy.orm import Session

from ..models import DreamMutation, DreamRun, Memory, Observation
from .dream_engine import PALETTE, build_memory_key, memory_position, refresh_memory_freshness


def _ago(hours: int) -> datetime:
  return datetime.utcnow() - timedelta(hours=hours)


SEED_MEMORIES = [
  {
    "scope_type": "user",
    "scope_id": "u_mira",
    "memory_type": "feedback",
    "cluster_key": "mira-clarity",
    "title": "Collaboration Signal: Mira Clarity",
    "summary": "Mira responds best to direct, compact answers with no decorative wrap-up.",
    "body": "Dream synthesis\n\n- Keep responses short.\n- Put the practical move first.\n- Skip ceremonial summaries unless asked.",
    "strength": 0.94,
    "source_count": 5,
    "tags": ["concise", "communication", "mira"],
    "updated_at": _ago(10),
  },
  {
    "scope_type": "project",
    "scope_id": "p_lighthouse",
    "memory_type": "project",
    "cluster_key": "launch-freeze",
    "title": "Project Orbit: Launch Freeze",
    "summary": "Lighthouse freezes non-critical schema work during launch week.",
    "body": "Dream synthesis\n\n- Avoid opportunistic migrations near launch.\n- Prioritize rollback safety over elegance.",
    "strength": 0.88,
    "source_count": 4,
    "tags": ["release", "migration", "freeze"],
    "updated_at": _ago(18),
  },
  {
    "scope_type": "team",
    "scope_id": "team_nocturne",
    "memory_type": "reference",
    "cluster_key": "orbit-linear",
    "title": "Reference Beacon: Orbit Linear",
    "summary": "Incidents for the Nocturne team live in the ORBIT Linear board.",
    "body": "Dream synthesis\n\n- Use ORBIT for incident context.\n- If a thread smells like latency or paging, check ORBIT first.",
    "strength": 0.79,
    "source_count": 3,
    "tags": ["linear", "incident", "orbit"],
    "updated_at": _ago(20),
  },
  {
    "scope_type": "user",
    "scope_id": "u_orion",
    "memory_type": "user",
    "cluster_key": "orion-traceability",
    "title": "User Portrait: Orion Traceability",
    "summary": "Orion values traceability and wants rationale kept attached to operational decisions.",
    "body": "Dream synthesis\n\n- Show why a recommendation exists.\n- Tie suggestions back to an observable constraint.",
    "strength": 0.82,
    "source_count": 4,
    "tags": ["audit", "traceability", "orion"],
    "updated_at": _ago(28),
  },
  {
    "scope_type": "project",
    "scope_id": "p_lighthouse",
    "memory_type": "project",
    "cluster_key": "legal-over-ergonomics",
    "title": "Project Orbit: Legal Over Ergonomics",
    "summary": "When compliance and developer convenience conflict, Lighthouse takes the compliance path.",
    "body": "Dream synthesis\n\n- Session token handling is a compliance-first surface.\n- Prefer defensible controls over elegant shortcuts.",
    "strength": 0.91,
    "source_count": 5,
    "tags": ["compliance", "security", "sessions"],
    "updated_at": _ago(32),
  },
  {
    "scope_type": "team",
    "scope_id": "team_nocturne",
    "memory_type": "reference",
    "cluster_key": "latency-dashboard",
    "title": "Reference Beacon: Latency Dashboard",
    "summary": "The on-call latency truth lives on the `spectra-latency` Grafana board.",
    "body": "Dream synthesis\n\n- Request-path changes should be checked against spectra-latency.\n- It is the dashboard that pages people.",
    "strength": 0.76,
    "source_count": 3,
    "tags": ["grafana", "latency", "oncall"],
    "updated_at": _ago(38),
  },
  {
    "scope_type": "user",
    "scope_id": "u_mira",
    "memory_type": "user",
    "cluster_key": "mira-night-ritual",
    "title": "User Portrait: Mira Night Ritual",
    "summary": "Mira reviews hard decisions late at night and prefers summaries framed as choices, not verdicts.",
    "body": "Dream synthesis\n\n- Offer options.\n- Keep trade-offs visible.\n- Leave room for authorship.",
    "strength": 0.71,
    "source_count": 2,
    "tags": ["night", "decision-making", "mira"],
    "updated_at": _ago(48),
  },
  {
    "scope_type": "project",
    "scope_id": "p_lighthouse",
    "memory_type": "feedback",
    "cluster_key": "no-repeat-questions",
    "title": "Collaboration Signal: No Repeat Questions",
    "summary": "Lighthouse operators should not ask customers to re-send material already present in the case file.",
    "body": "Dream synthesis\n\n- Search the case context before asking for documents again.\n- Repetition reads as negligence in sensitive queues.",
    "strength": 0.84,
    "source_count": 4,
    "tags": ["support", "intake", "customer-care"],
    "updated_at": _ago(70),
  },
]


SEED_OBSERVATIONS = [
  {
    "source": "chat",
    "kind": "feedback_signal",
    "scope_type": "user",
    "scope_id": "u_mira",
    "title": "Mira cut the flourish",
    "content": "Mira asked for the answer first and the framing second.",
    "importance": 0.92,
    "confidence": 0.94,
    "tags": ["concise", "communication", "mira"],
    "cluster_key": "mira-clarity",
    "type_hint": "feedback",
    "processed": True,
    "created_at": _ago(90),
  },
  {
    "source": "chat",
    "kind": "preference_signal",
    "scope_type": "user",
    "scope_id": "u_mira",
    "title": "Mira dislikes trailing summaries",
    "content": "Closing summaries feel redundant to Mira when the diff already says enough.",
    "importance": 0.86,
    "confidence": 0.91,
    "tags": ["concise", "summary", "mira"],
    "cluster_key": "mira-clarity",
    "type_hint": "feedback",
    "processed": True,
    "created_at": _ago(72),
  },
  {
    "source": "incident_postmortem",
    "kind": "project_signal",
    "scope_type": "project",
    "scope_id": "p_lighthouse",
    "title": "Launch freeze reaffirmed",
    "content": "The launch captain blocked two schema changes to keep rollback paths clean.",
    "importance": 0.83,
    "confidence": 0.88,
    "tags": ["release", "migration", "freeze"],
    "cluster_key": "launch-freeze",
    "type_hint": "project",
    "processed": True,
    "created_at": _ago(68),
  },
  {
    "source": "linear",
    "kind": "reference_signal",
    "scope_type": "team",
    "scope_id": "team_nocturne",
    "title": "ORBIT remains the incident ledger",
    "content": "All paging incidents for Nocturne are still tracked in Linear project ORBIT.",
    "importance": 0.74,
    "confidence": 0.89,
    "tags": ["linear", "incident", "orbit"],
    "cluster_key": "orbit-linear",
    "type_hint": "reference",
    "processed": True,
    "created_at": _ago(64),
  },
  {
    "source": "chat",
    "kind": "profile_signal",
    "scope_type": "user",
    "scope_id": "u_orion",
    "title": "Orion asked for a decision trail",
    "content": "Orion wants every operational recommendation tied back to the reason it exists.",
    "importance": 0.8,
    "confidence": 0.88,
    "tags": ["audit", "traceability", "orion"],
    "cluster_key": "orion-traceability",
    "type_hint": "user",
    "processed": True,
    "created_at": _ago(60),
  },
  {
    "source": "security_review",
    "kind": "project_signal",
    "scope_type": "project",
    "scope_id": "p_lighthouse",
    "title": "Compliance won the auth debate",
    "content": "The auth middleware rewrite is driven by legal constraints around session storage.",
    "importance": 0.91,
    "confidence": 0.93,
    "tags": ["compliance", "security", "sessions"],
    "cluster_key": "legal-over-ergonomics",
    "type_hint": "project",
    "processed": True,
    "created_at": _ago(58),
  },
  {
    "source": "grafana",
    "kind": "reference_signal",
    "scope_type": "team",
    "scope_id": "team_nocturne",
    "title": "Spectra latency stayed authoritative",
    "content": "The `spectra-latency` Grafana board is still the first stop for request-path changes.",
    "importance": 0.77,
    "confidence": 0.87,
    "tags": ["grafana", "latency", "oncall"],
    "cluster_key": "latency-dashboard",
    "type_hint": "reference",
    "processed": True,
    "created_at": _ago(52),
  },
  {
    "source": "chat",
    "kind": "profile_signal",
    "scope_type": "user",
    "scope_id": "u_mira",
    "title": "Mira asks for choices at night",
    "content": "Late-night reviews land better when framed as options rather than a single decree.",
    "importance": 0.68,
    "confidence": 0.81,
    "tags": ["night", "decision-making", "mira"],
    "cluster_key": "mira-night-ritual",
    "type_hint": "user",
    "processed": True,
    "created_at": _ago(50),
  },
  {
    "source": "support_case",
    "kind": "feedback_signal",
    "scope_type": "project",
    "scope_id": "p_lighthouse",
    "title": "Duplicate intake caused friction",
    "content": "Customers escalated when agents re-requested documents already attached to the case file.",
    "importance": 0.86,
    "confidence": 0.92,
    "tags": ["support", "intake", "customer-care"],
    "cluster_key": "no-repeat-questions",
    "type_hint": "feedback",
    "processed": True,
    "created_at": _ago(46),
  },
  {
    "source": "chat",
    "kind": "feedback_signal",
    "scope_type": "user",
    "scope_id": "u_mira",
    "title": "Mira still wants the clean cut",
    "content": "A proposed reply with a long epilogue was rejected; Mira asked for the shorter version.",
    "importance": 0.9,
    "confidence": 0.95,
    "tags": ["concise", "communication", "mira"],
    "cluster_key": "mira-clarity",
    "type_hint": "feedback",
    "processed": False,
    "created_at": _ago(18),
  },
  {
    "source": "calendar",
    "kind": "project_signal",
    "scope_type": "project",
    "scope_id": "p_lighthouse",
    "title": "Moonshot release enters quiet week",
    "content": "The Moonshot release branch cuts next Thursday; non-critical merges should slow down now.",
    "importance": 0.88,
    "confidence": 0.9,
    "tags": ["release", "branch", "freeze"],
    "cluster_key": "launch-freeze",
    "type_hint": "project",
    "processed": False,
    "created_at": _ago(16),
  },
  {
    "source": "chat",
    "kind": "project_signal",
    "scope_type": "project",
    "scope_id": "p_lighthouse",
    "title": "Consent logs became a blocker",
    "content": "Legal said consent audit logs must survive redact workflows, even if that makes the pipeline heavier.",
    "importance": 0.93,
    "confidence": 0.89,
    "tags": ["compliance", "audit", "consent"],
    "cluster_key": "consent-audit-logs",
    "type_hint": "project",
    "processed": False,
    "created_at": _ago(15),
  },
  {
    "source": "slack",
    "kind": "reference_signal",
    "scope_type": "team",
    "scope_id": "team_nocturne",
    "title": "Escalations route through midnight watch",
    "content": "The `#midnight-watch` Slack channel is where live escalations get picked up fastest.",
    "importance": 0.75,
    "confidence": 0.86,
    "tags": ["slack", "escalation", "support"],
    "cluster_key": "midnight-watch",
    "type_hint": "reference",
    "processed": False,
    "created_at": _ago(14),
  },
  {
    "source": "chat",
    "kind": "profile_signal",
    "scope_type": "user",
    "scope_id": "u_orion",
    "title": "Orion wants citations with warnings",
    "content": "When a recommendation is risky, Orion wants the warning and the rationale on the same line.",
    "importance": 0.71,
    "confidence": 0.84,
    "tags": ["audit", "traceability", "warnings"],
    "cluster_key": "orion-traceability",
    "type_hint": "user",
    "processed": False,
    "created_at": _ago(12),
  },
  {
    "source": "support_case",
    "kind": "feedback_signal",
    "scope_type": "project",
    "scope_id": "p_lighthouse",
    "title": "Avoid asking for already-uploaded passports",
    "content": "The queue lost trust after two customers were asked for passports that were already in the dossier.",
    "importance": 0.89,
    "confidence": 0.93,
    "tags": ["support", "intake", "passport"],
    "cluster_key": "no-repeat-questions",
    "type_hint": "feedback",
    "processed": False,
    "created_at": _ago(10),
  },
  {
    "source": "figma",
    "kind": "reference_signal",
    "scope_type": "team",
    "scope_id": "team_nocturne",
    "title": "The dream map lives in Figma file Nebula Room",
    "content": "System-wide visual language is currently documented in the shared Figma file `Nebula Room`.",
    "importance": 0.62,
    "confidence": 0.82,
    "tags": ["figma", "design-system", "reference"],
    "cluster_key": "nebula-room",
    "type_hint": "reference",
    "processed": False,
    "created_at": _ago(8),
  },
  {
    "source": "chat",
    "kind": "profile_signal",
    "scope_type": "user",
    "scope_id": "u_lyra",
    "title": "Lyra is new to the frontend surface",
    "content": "Lyra has deep backend experience but wants frontend explanations mapped to state transitions and constraints.",
    "importance": 0.7,
    "confidence": 0.83,
    "tags": ["frontend", "backend", "learning"],
    "cluster_key": "lyra-frontend-bridge",
    "type_hint": "user",
    "processed": False,
    "created_at": _ago(7),
  },
  {
    "source": "retro",
    "kind": "feedback_signal",
    "scope_type": "team",
    "scope_id": "team_nocturne",
    "title": "Real database tests are mandatory for auth paths",
    "content": "Mocks hid a migration bug before; the team now requires real database integration tests for auth flows.",
    "importance": 0.95,
    "confidence": 0.97,
    "tags": ["testing", "database", "auth"],
    "cluster_key": "real-db-tests",
    "type_hint": "feedback",
    "processed": False,
    "created_at": _ago(6),
  },
  {
    "source": "postmortem",
    "kind": "project_signal",
    "scope_type": "project",
    "scope_id": "p_lighthouse",
    "title": "Retry storms traced to duplicate webhook signatures",
    "content": "Webhooks are now treated as idempotency-sensitive because duplicate signatures triggered retry storms.",
    "importance": 0.84,
    "confidence": 0.87,
    "tags": ["webhooks", "retries", "idempotency"],
    "cluster_key": "webhook-idempotency",
    "type_hint": "project",
    "processed": False,
    "created_at": _ago(5),
  },
  {
    "source": "chat",
    "kind": "feedback_signal",
    "scope_type": "user",
    "scope_id": "u_mira",
    "title": "Mira approved the single bundled patch",
    "content": "For this surface area, Mira preferred one coherent patch over several tiny pull requests.",
    "importance": 0.67,
    "confidence": 0.8,
    "tags": ["pr-strategy", "cohesion", "mira"],
    "cluster_key": "mira-bundled-pr",
    "type_hint": "feedback",
    "processed": False,
    "created_at": _ago(4),
  },
]


def seed_demo_data(session: Session) -> None:
  existing = session.scalar(select(Observation.id).limit(1))
  if existing is not None:
    return

  historical_run = DreamRun(
    mode="historical",
    status="completed",
    summary="The first night gathered the founding constellation.",
    observations_seen=9,
    memories_created=len(SEED_MEMORIES),
    memories_updated=0,
    memories_archived=0,
    created_at=_ago(40),
    completed_at=_ago(39),
  )
  session.add(historical_run)
  session.flush()

  for seed in SEED_MEMORIES:
    key = build_memory_key(
      seed["scope_type"],
      seed["scope_id"],
      seed["memory_type"],
      seed["cluster_key"],
    )
    x, y = memory_position(key)
    memory = Memory(
      key=key,
      memory_type=seed["memory_type"],
      scope_type=seed["scope_type"],
      scope_id=seed["scope_id"],
      title=seed["title"],
      summary=seed["summary"],
      body=seed["body"],
      strength=seed["strength"],
      source_count=seed["source_count"],
      tags=seed["tags"],
      color=PALETTE[seed["memory_type"]],
      neuron_x=x,
      neuron_y=y,
      last_dreamed_at=seed["updated_at"],
      created_at=seed["updated_at"] - timedelta(hours=18),
      updated_at=seed["updated_at"],
    )
    refresh_memory_freshness(memory)
    session.add(memory)
    session.flush()
    historical_run.mutations.append(
      DreamMutation(
        action="create",
        title=memory.title,
        rationale="Seeded as part of the founding constellation.",
        before_state=None,
        after_state={"summary": memory.summary, "strength": memory.strength},
        memory=memory,
      )
    )

  for seed in SEED_OBSERVATIONS:
    observation = Observation(**seed)
    session.add(observation)

  session.commit()

